// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8GRmVmHG1W0ErunKzMJ-jPEGRXYrRl0s',
    appId: '1:508994507198:android:45d30b8dcc498e6b8969ef',
    messagingSenderId: '508994507198',
    projectId: 'medicaladvisoryapp',
    storageBucket: 'medicaladvisoryapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpvabSW73spfcZMWTwlOzjUaRshwEEdto',
    appId: '1:508994507198:ios:8006130e3637a5ed8969ef',
    messagingSenderId: '508994507198',
    projectId: 'medicaladvisoryapp',
    storageBucket: 'medicaladvisoryapp.appspot.com',
    androidClientId: '508994507198-gbbq5m1ic270ms83ckcr1920djh85bvu.apps.googleusercontent.com',
    iosClientId: '508994507198-2tjs8ac9q1oul18120k4doobss8hn705.apps.googleusercontent.com',
    iosBundleId: 'y',
  );

}